name: test

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: true
        matrix:
          node: [21, 22, 23, 24]

    name: Run tests on Node v${{ matrix.node }} 
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: npm ci
    
      - name: build
        run: npm run build
    
      - name: test
        run: npm run test